# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: docker:latest
stages:
  - build

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache


deploy to production:
  image: docker:latest
  services:
    - docker:dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
    DOCKER_DRIVER: overlay
  before_script:
#    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  stage: build
  script:
    - docker build -t $IMAGE_TAG .
#    - docker push $IMAGE_TAG
  only:
    - master
  tags:
    - container-factory