# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
stages:
  - build

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache


deploy to production:
  image: scaleway/cli:latest
  variables:
    IMAGE_TAG: coolya/avr-gcc:latest
    SCW_SERVER_NAME: buildbob
    DOCKER_DRIVER: overlay
  before_script:
#    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - login -t $SCW_TOKEN
  stage: build
  script:
    - create --commercial-type=X64-120GB  --ip-address=dynamic --name="$SCW_SERVER_NAME" docker
    - start $SCW_SERVER_NAME -w
    - exec $SCW_SERVER_NAME "cd /tmp && git clone https://git.logv.ws/coolya/avr-gcc.git && cd avr-gcc && git checkout $CI_COMMIT_SHA"
    - exec $SCW_SERVER_NAME "cd /tmp/avr-gcc && docker build -t $IMAGE_TAG ./7.1"
    - exec $SCW_SERVER_NAME "rm -rf /tmp/avr-gcc"
    - stop $SCW_SERVER_NAME -w -t
#    - docker push $IMAGE_TAG
  only:
    - master